image:
  name: git.keithley.com:5050/trebuchet/teaspoon/teaspoon-build:latest
  entrypoint: [""]

include:
  # https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml


variables:
  NODE_EXTRA_CA_CERTS: "/etc/ssl/certs/ca-certificates.crt"

stages:
  - package
  - deploy

package:
  stage: package
  script:
    - cd WebHelpDocs
    - npm pack
  artifacts:
    name: npm-package
    paths:
      - ./WebHelpDocs/*.tgz
deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - package
  script:
    - cd WebHelpDocs
    - npm config set @trebuchet:registry "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
    - npm publish *.tgz

release:
  stage: deploy
  image: git.keithley.com:5050/gitlab-support/gitlab-release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - package
  script:
    - echo "release"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "keithley_instrument_libraries $CI_COMMIT_TAG release"
    description: |
      ## :warning: Disclaimer :warning:
      This is an _alpha_ stage project and should **NOT** be used for production use-cases.
      This project is **NOT** ready for customer usage. If there is a need to use this with a customer, please contact someone from the Teaspoon team to discuss options.

      ## Features Requests / Bugs
      If you find issues or have a feature request, please enter a [new issue on GitLab](https://git.keithley.com/trebuchet/teaspoon/web-help-documents/-/issues/new).
      This will allow us to filter the issues into JIRA to avoid duplicates and keep things focused.

      ## Added Features
      - __TBD__

      ## Known Issues
      - __TBD__

    ref: "$CI_COMMIT_TAG"


